import type { Locale } from './home'

export const accountPageCopy = {
  fr: {
    metaTitle: 'Mon espace, Lab Horizon',
    loading: 'Chargement de votre espace…',
    error: 'Impossible de charger votre espace.',
    greeting: (name: string) => `Bonjour, ${name}`,
    newPublication: 'Nouvelle pub.',
    drafts: 'Brouillons',
    watch: 'Veille',
    stats: { views: 'Vues', publications: 'Publications', watchNew: 'Veille' },
    tabs: { veille: 'Veille', publications: 'Publications', profil: 'Profil' },
    watchNew: (n: number) => (n > 0 ? `${n} nouvelles` : 'À jour'),
    reviewCta: 'Valider la vulgarisation',
    status: {
      DRAFT: 'Brouillon',
      PENDING_AI_VALIDATION: 'À valider',
      PUBLISHED: 'Publiée',
    },
    profileUnavailable: 'Votre profil sera disponible ici prochainement.',
    demoBanner:
      'Cet espace est en cours de déploiement, vos données seront synchronisées avec la plateforme institutionnelle.',
    logout: 'Déconnexion',
    nav: { dashboard: 'Tableau de bord', search: 'Recherche', publicSite: 'Site public' },
  },
  en: {
    metaTitle: 'My space, Lab Horizon',
    loading: 'Loading your space…',
    error: 'Unable to load your space.',
    greeting: (name: string) => `Hello, ${name}`,
    newPublication: 'New pub.',
    drafts: 'Drafts',
    watch: 'Watchlist',
    stats: { views: 'Views', publications: 'Publications', watchNew: 'Watchlist' },
    tabs: { veille: 'Watchlist', publications: 'Publications', profil: 'Profile' },
    watchNew: (n: number) => (n > 0 ? `${n} new` : 'Up to date'),
    reviewCta: 'Review plain-language version',
    status: {
      DRAFT: 'Draft',
      PENDING_AI_VALIDATION: 'To review',
      PUBLISHED: 'Published',
    },
    profileUnavailable: 'Your profile will be available here soon.',
    demoBanner:
      'This space is being rolled out, your data will sync with the institutional platform.',
    logout: 'Sign out',
    nav: { dashboard: 'Dashboard', search: 'Search', publicSite: 'Public site' },
  },
} as const satisfies Record<Locale, Record<string, unknown>>

export const publicationReviewCopy = {
  fr: {
    metaTitle: 'Validation vulgarisation, Lab Horizon',
    loading: 'Chargement…',
    error: 'Impossible de charger la proposition.',
    notFound: 'Publication introuvable.',
    title: 'Vérifiez que nous avons bien compris votre sujet',
    lead: 'Nous avons vulgarisé votre travail pour le rendre accessible au plus grand nombre. Relisez-le, corrigez-le si nécessaire, puis validez pour publier.',
    originalLabel: 'Titre scientifique',
    vulgarizedLabel: 'Titre vulgarisé',
    bodyLabel: 'Résumé vulgarisé',
    accept: 'Valider et publier',
    back: 'Retour au tableau de bord',
    success: 'Publication validée, elle sera visible du grand public.',
    pendingNote:
      'Proposition de vulgarisation générée par Lab Horizon, veuillez la relire avant publication.',
  },
  en: {
    metaTitle: 'Plain-language review, Lab Horizon',
    loading: 'Loading…',
    error: 'Unable to load the proposal.',
    notFound: 'Publication not found.',
    title: 'Please verify that we understood your topic correctly',
    lead: 'We have produced a plain-language version of your work for a broad audience. Review it, edit if necessary, then approve to publish.',
    originalLabel: 'Scientific title',
    vulgarizedLabel: 'Plain-language title',
    bodyLabel: 'Plain-language summary',
    accept: 'Approve and publish',
    back: 'Back to dashboard',
    success: 'Publication approved, it will be visible to the public.',
    pendingNote:
      'Plain-language proposal generated by Lab Horizon, please review before publishing.',
  },
} as const satisfies Record<Locale, Record<string, unknown>>
